import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsIn,
  IsISO8601,
  IsObject,
  IsUUID,
  ValidateNested,
} from "class-validator";
import { EVENT_TYPES } from "@ai-defense/event-schemas";

/**
 * REQ-9.6/9.16: one event in a synchronization batch. `eventId` is
 * generated by the edge agent when the event first enters its local
 * buffer (docs/mvp-plan/PRD-Phase-9.md REQ-9.5) and reused unchanged
 * across every retry — the same "generate once, reuse across
 * redelivery" discipline REQ-3.6's outbox rows already follow — so
 * `EdgeEventsService`'s idempotency check (REQ-9.7) recognizes a
 * redelivered batch correctly.
 */
export class EdgeEventDto {
  @ApiProperty({ format: "uuid" })
  @IsUUID()
  eventId!: string;

  // Only DEVICE_HEALTH_REPORTED is accepted in this pass — see
  // edge-event.types.ts's module docstring for why edge-produced
  // detections aren't ingested through this same endpoint yet.
  @ApiProperty({ enum: [EVENT_TYPES.DEVICE_HEALTH_REPORTED] })
  @IsIn([EVENT_TYPES.DEVICE_HEALTH_REPORTED])
  eventType!: string;

  @ApiProperty({
    description: "When the edge agent recorded this event, ISO 8601.",
  })
  @IsISO8601()
  occurredAt!: string;

  @ApiProperty({
    description:
      "Shape matches the eventType's payload contract in @ai-defense/event-schemas (e.g. DeviceHealthReportedPayload).",
  })
  @IsObject()
  payload!: Record<string, unknown>;
}

const MAX_BATCH_SIZE = 100;

/** REQ-9.16: batches are capped so a single request stays small even on a constrained link — the edge agent's own sync client further sub-batches below this cap when bandwidth is scarce. */
export class IngestEdgeEventsDto {
  @ApiProperty({ type: [EdgeEventDto] })
  @ValidateNested({ each: true })
  @Type(() => EdgeEventDto)
  @ArrayMinSize(1)
  @ArrayMaxSize(MAX_BATCH_SIZE)
  events!: EdgeEventDto[];
}
