/**
 * Phase 6 (docs/mvp-plan/PRD-Phase-6.md REQ-6.6): hand-written mirror of
 * `apps/api`'s response/request DTOs.
 *
 * These are hand-written, not generated by `@rtk-query/codegen-openapi`
 * against `packages/contracts/openapi.json` — that spec was last
 * exported before this phase's new endpoints (detections, audit-log)
 * existed, and regenerating it requires `nest build`, which needs the
 * new `@nestjs/websockets`/`socket.io` dependencies this sandbox can't
 * install (see docs/roadmap/Progress.md's Phase 6 Known gaps). Every
 * shape below was copied directly from the real DTO source file it
 * mirrors (comment above each type says which). Once a machine with
 * working `pnpm install` re-exports the OpenAPI spec, run
 * `pnpm --filter @ai-defense/web run codegen:api` and replace this file
 * with the generated one — `apiSlice.ts` only depends on the type names
 * below, not on them being hand-written.
 */

/** apps/api/src/missions/mission-state-machine.ts's `MissionStatus` (mirrors the Prisma enum). */
export const MISSION_STATUS = {
  DRAFT: "DRAFT",
  QUEUED: "QUEUED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;
export type MissionStatus = (typeof MISSION_STATUS)[keyof typeof MISSION_STATUS];

/** apps/api/src/roles/roles.constants.ts's `ROLE_NAMES`. */
export const ROLE_NAMES = {
  OPERATOR: "operator",
  ADMIN: "admin",
} as const;
export type RoleName = (typeof ROLE_NAMES)[keyof typeof ROLE_NAMES];

/** apps/api/src/auth/dto/auth-response.dto.ts */
export interface AuthUser {
  id: string;
  email: string;
  displayName: string;
  roles: RoleName[];
}

export interface AuthResponse {
  accessToken: string;
  expiresInSeconds: number;
  user: AuthUser;
}

/** apps/api/src/auth/dto/login.dto.ts */
export interface LoginRequest {
  email: string;
  password: string;
}

/** apps/api/src/auth/dto/register.dto.ts */
export interface RegisterRequest {
  email: string;
  password: string;
  displayName: string;
}

/** apps/api/src/missions/dto/mission-response.dto.ts */
export interface Mission {
  id: string;
  title: string;
  description: string | null;
  status: MissionStatus;
  videoObjectKey: string | null;
  createdById: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
}

/** apps/api/src/missions/dto/create-mission.dto.ts */
export interface CreateMissionRequest {
  title: string;
  description?: string;
}

/** apps/api/src/missions/dto/update-mission-metadata.dto.ts */
export interface UpdateMissionMetadataRequest {
  title?: string;
  description?: string;
}

/** apps/api/src/missions/dto/transition-mission.dto.ts */
export interface TransitionMissionRequest {
  targetState: MissionStatus;
}

/** apps/api/src/storage/dto/create-upload-url.dto.ts */
export interface CreateUploadUrlRequest {
  fileName: string;
  contentType: string;
}

/** apps/api/src/storage/dto/signed-url-response.dto.ts */
export interface SignedUrlResponse {
  url: string;
  objectKey: string;
  expiresAt: string;
}

/** apps/api/src/detections/dto/detection-response.dto.ts */
export interface DetectionBoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Detection {
  id: string;
  missionId: string;
  frameIndex: number;
  frameTimestampMs: number;
  trackId: number;
  label: string;
  confidence: number;
  boundingBox: DetectionBoundingBox;
  createdAt: string;
}

/** apps/api/src/audit/dto/audit-log-response.dto.ts */
export interface AuditLogEntry {
  id: string;
  actorUserId: string | null;
  action: string;
  targetType: string;
  targetId: string | null;
  missionId: string | null;
  correlationId: string | null;
  metadata: unknown;
  createdAt: string;
}

/**
 * apps/api/src/telemetry/dto/telemetry-response.dto.ts — a single
 * GeoJSON `Feature<LineString>` with parallel per-point property
 * arrays. `properties.approximate` is always `true` (REQ-7.7): this
 * platform never returns verified targeting coordinates, only
 * estimated ones, and that fact is part of the API contract itself,
 * not just a frontend convention.
 */
export interface TelemetryFeature {
  type: "Feature";
  geometry: {
    type: "LineString";
    coordinates: [number, number][];
  };
  properties: {
    missionId: string;
    pointCount: number;
    approximate: true;
    timestamps: string[];
    altitudesM: (number | null)[];
    headingsDeg: (number | null)[];
    speedsMps: (number | null)[];
  };
}

/** apps/api/src/telemetry/dto/telemetry-ingest-response.dto.ts */
export interface TelemetryIngestResponse {
  missionId: string;
  pointCount: number;
}

/**
 * Mirrors `packages/event-schemas`'s `ProcessingCompletedPayload`/
 * `ProcessingFailedPayload`/`ProcessingStartedPayload` fields the
 * frontend cares about — only what the WebSocket relay (REQ-6.5) and
 * the event timeline (REQ-6.14) actually read, not the full payload.
 */
export interface RealtimeMissionEvent {
  eventType: string;
  payload: {
    missionId: string;
    note?: string;
    reason?: string;
    frameCount?: number;
    detectionCount?: number;
    trackCount?: number;
    processingDurationMs?: number;
  } & Record<string, unknown>;
}
